export const DEFAULT_PUZZLE = {
  width: 15,
  height: 15,
  grid: [
    [
      {
        solution: { content: 'T', isBlack: false, number: '1' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '2' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'M', isBlack: false, number: '3' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'P', isBlack: false, number: '4' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'S', isBlack: false, number: '5' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'M', isBlack: false, number: '6' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '7' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'S', isBlack: false, number: '8' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '9' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '10' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '11' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '12' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'W', isBlack: false, number: '13' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: 'I', isBlack: false, number: '14' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'C', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'U', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'D', isBlack: false, number: '15' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'D', isBlack: false, number: '16' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: 'L', isBlack: false, number: '17' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'K', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'G', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'U', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'P', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '18' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'B', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: 'D', isBlack: false, number: '19' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'R', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'M', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'C', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'R', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'W', isBlack: false, number: '20' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'K', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: 'E', isBlack: false, number: '21' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'D', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'S', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '22' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'G', isBlack: false, number: '23' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '24' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'H', isBlack: false, number: '25' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '26' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'M', isBlack: false, number: '27' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'S', isBlack: false, number: '28' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'R', isBlack: false, number: '29' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'C', isBlack: false, number: '30' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '31' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'U', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'M', isBlack: false, number: '32' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'M', isBlack: false, number: '33' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'V', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'M', isBlack: false, number: '34' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'M', isBlack: false, number: '35' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'P', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'R', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'V', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'G', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: 'B', isBlack: false, number: '36' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'G', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'S', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: 'A', isBlack: false, number: '37' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '38' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '39' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'S', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: 'R', isBlack: false, number: '40' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'C', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '41' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'P', isBlack: false, number: '42' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'D', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '43' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'C', isBlack: false, number: '44' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '45' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'S', isBlack: false, number: '46' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '47' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: 'I', isBlack: false, number: '48' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'M', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'G', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '49' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'S', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'G', isBlack: false, number: '50' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '51' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '52' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'G', isBlack: false, number: '53' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'U', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'P', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: 'L', isBlack: false, number: '54' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'C', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'C', isBlack: false, number: '55' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'W', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'K', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: 'L', isBlack: false, number: '56' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'O', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'H', isBlack: false, number: '57' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'A', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'R', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'V', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
    [
      {
        solution: { content: 'A', isBlack: false, number: '58' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'S', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'L', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'I', isBlack: false, number: '59' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'N', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'S', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: '', isBlack: true, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '60' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'S', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'T', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'E', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
      {
        solution: { content: 'R', isBlack: false, number: '' },
        isBlack: false,
        content: '',
        number: '',
        wasChecked: false,
        wasRevealed: false,
        circle: false,
      },
    ],
  ],
  cursor: { row: 0, col: 0, direction: 'across' },
  time: 0,
  clues: [
    { number: '1', direction: 'across', text: 'Presses (down)' },
    { number: '1', direction: 'down', text: 'Key symbol near "!"' },
    { number: '2', direction: 'down', text: 'Tough nut to crack' },
    { number: '3', direction: 'down', text: 'Sang part of "Old MacDonald"' },
    { number: '4', direction: 'down', text: "Beadlike bit on a surfer's necklace" },
    { number: '5', direction: 'down', text: 'Improbable' },
    { number: '6', direction: 'across', text: 'Org. for the Houston Dynamo and Austin F.C.' },
    { number: '6', direction: 'down', text: 'Ginormous' },
    {
      number: '7',
      direction: 'down',
      text: '___ Bassi, first woman to earn a doctorate in science (University of Bologna, 1732)',
    },
    { number: '8', direction: 'down', text: 'Garage brand' },
    { number: '9', direction: 'across', text: 'Along for the ride, say' },
    { number: '9', direction: 'down', text: 'Like some threats' },
    { number: '10', direction: 'down', text: '"Slow Hands" singer ___ Horan' },
    { number: '11', direction: 'down', text: 'Four on the floor?' },
    { number: '12', direction: 'down', text: 'Like tutoring, typically' },
    { number: '13', direction: 'down', text: 'Peaceful protest' },
    { number: '14', direction: 'across', text: '"Yeah, lunch now works for me"' },
    { number: '15', direction: 'down', text: 'Party org.' },
    { number: '16', direction: 'across', text: 'Taurasi who leads the W.N.B.A. in career scoring' },
    { number: '17', direction: 'across', text: 'Showing promise' },
    { number: '18', direction: 'across', text: 'Tag' },
    { number: '19', direction: 'across', text: "What you'd love to own and drive" },
    { number: '20', direction: 'across', text: 'Acknowledgment with a shrug' },
    { number: '20', direction: 'down', text: 'Pests for a grain farmer' },
    { number: '21', direction: 'across', text: '"This ___ here!"' },
    { number: '22', direction: 'across', text: 'Partner of day' },
    { number: '23', direction: 'down', text: 'Be sycophantic' },
    { number: '24', direction: 'across', text: '2014 Television Hall of Fame inductee' },
    { number: '25', direction: 'across', text: 'Spirals out over the winter holidays?' },
    { number: '26', direction: 'down', text: 'Had quite a trip?' },
    { number: '27', direction: 'down', text: 'Styles associated with the Beatles' },
    { number: '28', direction: 'down', text: 'Taken care of, with "out"' },
    { number: '29', direction: 'across', text: 'Endorsement, for short' },
    { number: '30', direction: 'down', text: '___ Cruz, so-called "Queen of Salsa"' },
    { number: '31', direction: 'across', text: 'Gymnast Mary ___ Retton' },
    {
      number: '32',
      direction: 'across',
      text: "Its members were collectively awarded Time magazine's 2017 Person of the Year",
    },
    { number: '32', direction: 'down', text: 'Hat tricks are seen in them' },
    { number: '33', direction: 'down', text: '"Thanks a ___!"' },
    { number: '34', direction: 'down', text: 'Parts of many rom-coms' },
    { number: '35', direction: 'across', text: 'Unearned advantage based on sex' },
    { number: '35', direction: 'down', text: 'Quick post-wedding getaway' },
    { number: '36', direction: 'across', text: 'Hit HBO series based on a Liane Moriarty novel' },
    { number: '36', direction: 'down', text: "World's largest pasta producer" },
    { number: '37', direction: 'across', text: 'What "minuscule" is often misspelled with' },
    { number: '38', direction: 'across', text: 'Stub hub?' },
    { number: '39', direction: 'across', text: 'Prep class subject, for short' },
    { number: '40', direction: 'across', text: 'Costa ___' },
    { number: '41', direction: 'down', text: 'Fire ___ (gemstone)' },
    { number: '42', direction: 'across', text: 'Activity common in nightclubs, in brief' },
    { number: '43', direction: 'down', text: '"Wasn\'t the first time enough?!"' },
    { number: '44', direction: 'across', text: 'Italian for "so"' },
    { number: '45', direction: 'down', text: 'Genre for Bridget Riley\'s "Shadow Play"' },
    { number: '46', direction: 'down', text: 'Crack' },
    { number: '47', direction: 'down', text: 'Aide for a cartoonist' },
    { number: '48', direction: 'across', text: 'Tab on a Google search' },
    { number: '49', direction: 'down', text: "It doesn't offer flights on Saturday mornings" },
    { number: '50', direction: 'across', text: 'Band together against' },
    { number: '51', direction: 'down', text: "Workers you wouldn't want to see in the office?" },
    { number: '52', direction: 'down', text: 'Group co-founded by Eazy-E' },
    { number: '53', direction: 'down', text: 'Splicing target' },
    { number: '54', direction: 'across', text: 'Lite' },
    { number: '55', direction: 'across', text: "Question that's rarely a sign of good news" },
    { number: '55', direction: 'down', text: 'X' },
    { number: '56', direction: 'across', text: 'Buncha' },
    { number: '57', direction: 'across', text: 'Get overly personal, perhaps' },
    { number: '58', direction: 'across', text: 'Environmentalist Adams' },
    { number: '59', direction: 'across', text: "They're good to know" },
    { number: '60', direction: 'across', text: 'Compound with a fruity smell' },
  ],
  symmetry: null,
  isAutonumbered: false,
  title: 'NY Times, Friday, June 25, 2021 ',
  author: 'Scott Earl / Will Shortz',
  copyright: '© 2021, The New York Times',
  note: '',
};
